#!/usr/bin/env python
# -*- coding: utf8 -*- 

from __future__ import print_function
import os
import sys
import re
import traceback
import subprocess
import pprint
import cStringIO
import time
from scapy.all import *

###### parse arguments
import argparse
parser = argparse.ArgumentParser(description='Multitrace 1.0 - multi protocol traceroute network analyser')
parser.add_argument('--max-ttl', type=int, default=32, help='Max number of hops, default %(default)s')
parser.add_argument('--start-ttl', type=int, default=1, help='Start hop, default %(default)s')
parser.add_argument('--interval', type=float, default=0, help='Interval between packets, default %(default)s')
parser.add_argument('--timeout', type=float, default=3, help='Timeout waiting for answers, default %(default)s')
parser.add_argument('host', help='Host to trace')
# parser.add_argument('--verbose', action='store_true', help='verbose output')
# parser.add_argument('--debug', action='store_true', help='debug output (shows commands that are executed)')
args = parser.parse_args()

host_ip=Net(args.host).choice()



#try to discover a hop using various methods, and return received answers
def discover_hop(host_ip, ttl):
    #basic parallel udp/tcp/icmp probe
    answers,unans=sr(
        [ 
            IP(dst=host_ip, ttl=ttl)/UDP(dport=44443+ttl),
            IP(dst=host_ip, ttl=ttl)/TCP(dport=44443+ttl, flags="S"),
            IP(dst=host_ip, ttl=ttl)/ICMP(),
        ],
        timeout=args.timeout, inter=args.interval, verbose=0
    )

    if answers:
        return (answers)

    #use other methods..

    return(None)


complete=False
for ttl in range(args.start_ttl,args.max_ttl):
    print("Hop ", ttl, ": ")
    answers=discover_hop(host_ip, ttl)


    if answers:
        for snd, recv in answers:
            print(" ",recv.summary())
            if snd.dst==recv.src:
                complete=True
    else:
        print("(timeout)")

    if complete:
        break
