#!/bin/bash

#(C)edwin@datux.nl -- GPL

NAME="$1"
HOSTS="$2"

[ "$NAME" ] || exit 1

nmaprun() {
    echo -en "Scanning...\r"
    nmap --stats-every 1 $@ | grep --line-buffered Timing: | while read LINE; do
        echo -en "$LINE       \r"
    done
    echo

}

grepips() {
    grep -v '#' "$1" | cut -f2 -d' '

}

PAD_LENGTH=$((COLS - max_length - 1))

SNAPSHOT="$NAME"
CURRENT="$NAME.current"
SCAN="$NAME.tmp"

if ! [ -e "$SNAPSHOT" ]; then
    echo "Creating initial scan snapshot ip list..."
    nmaprun -n -sn --open -oG "$SCAN" $HOSTS
    echo
    grepips "$SCAN" |sort  >"$SNAPSHOT"
    cp "$SNAPSHOT" "$CURRENT"
fi

tput reset

while true; do

    #screen layout
    MAX_LENGTH=16
    COLS=$(tput cols)
    ((PER_LINE = (COLS / MAX_LENGTH)))

    tput cup 0 0

    TOTAL=0
    OFFLINE=0
    THIS_LINE=0
    for IP in $(cat "$SNAPSHOT"); do
        ((TOTAL++))
        if ! grep -x "$IP" "$CURRENT" >/dev/null; then
            tput setab 1
            ((OFFLINE++))
        else
            tput setaf 2
        fi

        printf "%-${MAX_LENGTH}s" "$IP"
        tput sgr0

        ((THIS_LINE++))
        if [ $THIS_LINE -ge $PER_LINE ]; then
            THIS_LINE=0
            echo

        fi
    done
    tput ed
    echo
    echo "$OFFLINE/$TOTAL offline"

    nmaprun -n -sn --open -oG "$SCAN" -iL "$SNAPSHOT"
    grepips "$SCAN" >"$CURRENT"

done
