#!/usr/bin/env python2.7

#(C)2013 Edwin Eefting edwin@datux.nl

#parses stdin and updates pybar status when a certain regex matches

import subprocess
import re
import sys
import urllib2
import time

###### parse arguments
import argparse
parser = argparse.ArgumentParser(description='pyBar parser v1.0 (C)Edwin Eefting', formatter_class=argparse.RawDescriptionHelpFormatter, epilog="""
Example:

    tail -f /var/log/messages | ./pybar_parse --url http://192.168.13.1:8080 ssh,ok,"sshd.*Accepted.*root" ssh,caution,"sshd.*Failed" arp,ok,"sshd.*Accepted.*root" arp,caution,"arpwatch.*new station"

    This watches the logs for failed logins and new station on your network.

    You can reset the status back to "ok" by logging in as root. (and checking out the logfiles to see if there actually is going something on)

    """)
parser.add_argument('--url', nargs='?', default='http://localhost:8080', help='pybar url')
parser.add_argument('service',  nargs='+', default=[],  help='Service definition: name,prio,regex')

#parser.add_argument('--update', action='store_true', help='update existing users')
args = parser.parse_args()


def update_bar(url, service, prio):
    while 1:
        try:
            bar_url=url+"/"+service+"/"+prio+"/"
            print ("Calling "+bar_url)
            urllib2.urlopen(bar_url)
            print ("Done")
            break
        except Exception as e:
            print ("Opening "+url+" failed:"+str(e))
            time.sleep(2)
            print ("Retrying...")




services={}
for (service_nr,service) in enumerate(args.service):
    (name,prio,regex)=service.split(",")

    if name not in services:
        services[name]={}

    services[name][prio]=regex


for (name,service) in services.items():
    update_bar(args.url, name, "ok")

while 1:

    try:
        line=sys.stdin.readline()
    except KeyboardInterrupt:
    
        print("Exitting...")
        for (name, service) in services.items():
            update_bar(args.url, name, "del")
        sys.exit()

    if not line:
        break

    line=str(line)

    for (name,service) in services.items():

        if 'alert' in service and re.search(service['alert'], line):
            update_bar(args.url, name, "alert")
        elif 'caution' in service and re.search(service['caution'], line):
            update_bar(args.url, name, "caution")
        elif 'ok' in service and re.search(service['ok'], line):
            update_bar(args.url, name, "ok")



