#!/bin/bash

set -e

HOST=$1
DST=$2
NAME=$3

if [ "$NAME" == "" ]; then
    echo "Usage:"
    echo "$0 <host> <localfilesystem> <backupname>"
    echo
    echo "Use 'localhost' to operate locally"
    echo "Set the property 'autobackup:backupname' to true on the filesystems you want to backup"
    echo
    exit 1
fi

PROPERTY=autobackup:$NAME

#if you litterally specify localhost, it means its local without ssh
if [ "$HOST" == "localhost" ]; then
    REMOTE_CMD="eval"
else
    REMOTE_CMD="ssh $HOST"
fi
        


FILESYSTEMS=`$REMOTE_CMD "zfs get -t volume,filesystem -o name,value -H $PROPERTY | grep 'true$' | cut -f1"`

echo "Filesystems to backup:"
echo "$FILESYSTEMS"


for FILESYSTEM in $FILESYSTEMS; do
    echo 
    #create destination and parent of the filesystem?
    FILESYSTEM_PARENT=`echo $FILESYSTEM|sed 's@/[^/]*$@@'`
    zfs create -p $DST
    if [ "$FILESYSTEM_PARENT" != "$FILESYSTEM" ]; then
	echo "Creating parent $DST/$FILESYSTEM_PARENT"
        zfs create -p $DST/$FILESYSTEM_PARENT
    fi

    ./zfs_backup $HOST $FILESYSTEM $DST/$FILESYSTEM $NAME
done

echo "All backups done"
