#!/bin/bash
#ino build -m atmega328 && ino upload -m atmega328 &&  ino serial -- --imap lfcrlf
ino build -m atmega328 || exit 1

echo "######### PUSH RESET #######" 
if [ "$1" ]; then
	ino upload -p $1 -m atmega328 &&  ino serial -p $1 -- --omap crlf --echo
else
	ino upload -m atmega328 &&  ino serial -- --omap crlf --echo
fi


